### PR TITLE
Several improvements

### PR DESCRIPTION
**Pull request by hurricup**
These changes are necessary for IDE integration:

- do not print perl version header with single perl running (same as in perlbrew)
- proper proxying stderr to stderr
- `list` command
- async data proxying
- better params proxying

I don't know how to make a distro, so  need some attention

### CODE REVIEW

**Comment by stevieb9** [comment]
This is fantastic, thank you very much! I'm a bit busy with preparing to move, so I will get to this over the next coming couple of weeks.

Thanks again!

**Comment by stevieb9** [comment]
@pryrt The changes @hurricup has provided here all appear very sane and reasonable to me. I'm not in a position to test until at least next week.

Looks like a few more tests may need to be added and possibly some documentation updates (unsure about that for sure though), but I'm going to try to fastrack this PR as I heavily use the specific software that the PR author is trying to integrate with Berrybrew here ([Camelcade Perl5 Plugin for intelliJ IDE](https://github.com/Camelcade/Perl5-IDEA)).

My thought here is to pull the PR locally to a new branch created right off of master, merge it in, ensure tests run and everything looks sane, merge the PR, pull down master, and create a new build. After that we can just set up necessary issues to create new tests/docs if necessary.

**Comment by stevieb9** [comment]
@hurricup,

I've released v1.19 (https://github.com/stevieb9/berrybrew) that incorporates all of the changes in your PR.

Thanks!

**Comment by pryrt** [comment]
@stevieb9, sorry I didn't get in there and help more.  Hopefully, I'll be able to help with some of the issues that you (or others) have opened.  (Unfortunately, about the same time you asked me to help you provide support, a crunch-time hit at `$work`, and energy for spending time at `$home` on debug/development projects has waned somewhat.  I'll try to help out, but no promises on being super-prompt / next-day kind of responses.)

**Comment by stevieb9** [comment]
Absolutely no worries!

I know what it's like being sidetracked and very busy. The work that was
presented in the PR, I integrated yesterday fully (and made some other
slight modifications).

I've opened another series of issues I've been finding going through
code/docs, so I'm going to get these in today (and possibly this homedir
stuff as well). All trivial things though.

**Pull request merged**
